name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: ${{ secrets.GCP_REGION }}
      SERVICE_NAME: cloud-arena
      REPOSITORY: cloud-arena

    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_NAME }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker $REGION-docker.pkg.dev

      - name: Create Artifact Registry Repository
        run: |
          gcloud artifacts repositories describe $REPOSITORY \
            --location=$REGION \
            || \
          gcloud artifacts repositories create $REPOSITORY \
            --repository-format=docker \
            --location=$REGION \
            --description="Docker repository for Cloud Arena"

      - name: Build and Push
        run: |
          IMAGE="$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE_NAME:${{ github.sha }}"
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Deploy
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE_NAME:${{ github.sha }} \
            --region $REGION \
            --platform managed \
            --quiet

  
  destroy:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    
    env:
      REGION: ${{ secrets.GCP_REGION }}
      SERVICE_NAME: cloud-arena
      REPOSITORY: cloud-arena
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_NAME }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Destroy Cloud Run Service
        run: |
          gcloud run services delete $SERVICE_NAME \
            --region $REGION \
            --quiet
        continue-on-error: true

      - name: Destroy Artifact Registry Repository
        run: |
          gcloud artifacts repositories delete $REPOSITORY \
            --location=$REGION \
            --quiet
        continue-on-error: true